import mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, ImageRun } from 'docx';
import * as fs from 'fs';
import { Buffer } from 'buffer';

export interface DocxProcessingResult {
  html: string;
  styles: string[];
  images: { [key: string]: Buffer };
  metadata: {
    wordCount: number;
    pageCount: number;
    author?: string;
    title?: string;
    lastModified?: Date;
  };
}

export interface DocxExportOptions {
  title?: string;
  author?: string;
  subject?: string;
  description?: string;
  preserveStyles?: boolean;
}

export class DocxProcessor {
  /**
   * Parse DOCX file and extract content with full formatting
   */
  static async parseDocx(buffer: Buffer): Promise<DocxProcessingResult> {
    try {
      console.log('🔄 Starting DOCX parsing...');
      
      // Extract HTML content with styling
      const result = await mammoth.convertToHtml(
        { buffer },
        {
          convertImage: mammoth.images.imgElement(function(image) {
            return image.read("base64").then(function(imageBuffer) {
              // Store image data for later use
              return {
                src: `data:${image.contentType};base64,${imageBuffer}`
              };
            });
          }),
          includeEmbeddedStyleMap: true,
          includeDefaultStyleMap: true,
          styleMap: [
            "p[style-name='Heading 1'] => h1:fresh",
            "p[style-name='Heading 2'] => h2:fresh", 
            "p[style-name='Heading 3'] => h3:fresh",
            "p[style-name='Title'] => h1.title:fresh",
            "p[style-name='Subtitle'] => h2.subtitle:fresh",
            "p[style-name='Quote'] => blockquote:fresh",
            "r[style-name='Strong'] => strong:fresh",
            "r[style-name='Emphasis'] => em:fresh"
          ]
        }
      );

      // Extract metadata using mammoth's raw document access
      const rawResult = await mammoth.extractRawText({ buffer });
      const wordCount = rawResult.value.split(/\s+/).filter(word => word.length > 0).length;

      // Estimate page count (rough calculation)
      const pageCount = Math.max(1, Math.ceil(wordCount / 250));

      const processingResult: DocxProcessingResult = {
        html: result.value,
        styles: result.messages.map(msg => msg.message),
        images: {}, // Would be populated with actual image extraction
        metadata: {
          wordCount,
          pageCount,
          title: 'Resume Document',
          author: 'Resume Author',
          lastModified: new Date()
        }
      };

      console.log(`✅ DOCX parsed successfully: ${wordCount} words, ${pageCount} pages`);
      return processingResult;

    } catch (error) {
      console.error('💥 DOCX parsing failed:', error);
      throw new Error(`Failed to parse DOCX: ${error}`);
    }
  }

  /**
   * Convert HTML content back to DOCX with proper formatting
   */
  static async generateDocx(htmlContent: string, options: DocxExportOptions = {}): Promise<Buffer> {
    try {
      console.log('🔄 Starting DOCX generation...');

      // Parse HTML and convert to DOCX elements
      const paragraphs = this.htmlToDocxElements(htmlContent);

      // Create new document
      const doc = new Document({
        creator: options.author || "Resume Customizer Pro",
        title: options.title || "Resume Document",
        description: options.description || "Generated by Resume Customizer Pro",
        sections: [
          {
            properties: {
              page: {
                margin: {
                  top: 720,  // 0.5 inch
                  bottom: 720,
                  left: 720,
                  right: 720,
                },
                size: {
                  orientation: "portrait",
                  width: 12240, // 8.5 inch
                  height: 15840, // 11 inch
                },
              },
            },
            children: paragraphs,
          },
        ],
      });

      // Generate DOCX buffer
      const buffer = await Packer.toBuffer(doc);
      console.log('✅ DOCX generated successfully');
      return buffer;

    } catch (error) {
      console.error('💥 DOCX generation failed:', error);
      throw new Error(`Failed to generate DOCX: ${error}`);
    }
  }

  /**
   * Convert HTML elements to DOCX elements
   */
  private static htmlToDocxElements(html: string): Array<Paragraph | Table> {
    const elements: Array<Paragraph | Table> = [];
    
    // Simple HTML to DOCX conversion (this would be much more sophisticated in production)
    // Split by major HTML elements
    const htmlWithoutTags = html
      .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '') // Remove scripts
      .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, ''); // Remove styles

    // Parse common HTML elements
    const lines = htmlWithoutTags.split('\n').filter(line => line.trim());
    
    for (const line of lines) {
      if (line.includes('<h1')) {
        elements.push(new Paragraph({
          text: this.extractTextFromHtml(line),
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 }
        }));
      } else if (line.includes('<h2')) {
        elements.push(new Paragraph({
          text: this.extractTextFromHtml(line),
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 150 }
        }));
      } else if (line.includes('<h3')) {
        elements.push(new Paragraph({
          text: this.extractTextFromHtml(line),
          heading: HeadingLevel.HEADING_3,
          spacing: { after: 100 }
        }));
      } else if (line.includes('<li')) {
        elements.push(new Paragraph({
          text: `• ${this.extractTextFromHtml(line)}`,
          spacing: { after: 100 }
        }));
      } else if (line.trim() && !line.includes('<div') && !line.includes('</div>')) {
        // Regular paragraph
        const text = this.extractTextFromHtml(line);
        if (text.trim()) {
          elements.push(new Paragraph({
            children: [new TextRun(text)],
            spacing: { after: 120 }
          }));
        }
      }
    }

    // Ensure we have at least one paragraph
    if (elements.length === 0) {
      elements.push(new Paragraph({
        children: [new TextRun("Resume content")],
      }));
    }

    return elements;
  }

  /**
   * Extract plain text from HTML
   */
  private static extractTextFromHtml(html: string): string {
    return html
      .replace(/<[^>]*>/g, '') // Remove HTML tags
      .replace(/&nbsp;/g, ' ') // Replace HTML entities
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .trim();
  }

  /**
   * Validate DOCX file
   */
  static async validateDocx(buffer: Buffer): Promise<boolean> {
    try {
      await mammoth.extractRawText({ buffer });
      return true;
    } catch (error) {
      return false;
    }
  }
}